name: 'Determine Ambiente Baseado na Branch'
description: Seleciona o ambiente a ser usado e seus segredos conforme a branch que foi commitada
author: Victor Borges Silva
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  github_ref:
    description: 'Branch reference (GITHUB_REF)'
    required: true
runs:
  using: 'composite'
  steps:
    - run: chmod +x ./scripts/determina_ambiente.sh
      shell: bash
    - run: ./scripts/determina_ambiente.sh
      shell: bash
      working-directory: $GITHUB_WORKSPACE
      env:
        GITHUB_REF: ${{ inputs.github_ref }}
