name: 'Determine Ambiente Baseado na Branch'
description: Selectiona o ambiente a ser usado e seus segredos conforme a branch que foi commitada
author: Victor Borges Silva
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  github_ref:
    description: 'Branch reference (GITHUB_REF)'
    required: true
    default: '${{ github.ref }}'
runs:
  using: 'composite'
  steps:
    - run: ./determina_ambiente.sh
      shell: bash
      env:
        GITHUB_REF: ${{ inputs.github_ref }}
