name: Determine Environment
description: Determina o environment a ser usado baseado na branch
author: Victor Borges Silva
branding:
  icon: "check-square"    # Nome do ícone do Feather Icons
  color: "blue"           # Cor da action no Marketplace
inputs:
  main_branch:
    description: 'Nome da branch para o ambiente de Produção'
    required: true
    default: 'main'
  hml_branch:
    description: 'Nome da branch para o ambiente de Homologação'
    required: true
    default: 'hml'
  dev_branch:
    description: 'Nome da branch para o ambiente de Desenvolvimento'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: Configura environment baseado na branch
      shell: bash
      run: |
        echo "Determianndo environment baseado na branch: ${GITHUB_REF}"
        if [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.main_branch }}" ]]; then
          echo "ambiente=prd" >> $GITHUB_ENV
          echo "::set-output name=ambiente::prd"
           echo "Selected environment: prd"
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.hml_branch }}" ]]; then
          echo "ambiente=hml" >> $GITHUB_ENV
          echo "::set-output name=ambiente::hml"
           echo "Selected environment: hml"
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.dev_branch }}" ]]; then
          echo "ambiente=dev" >> $GITHUB_ENV
          echo "::set-output name=ambiente::dev"
           echo "Selected environment: dev"
        else
          echo "ambiente=hml" >> $GITHUB_ENV
          echo "::set-output name=ambiente::hml"
          echo "Selected environment: hml"
        fi

outputs:
  ambiente:
    description: 'Determina o environment baseado na branch commitada'