name: Determine Environment
description: Determina o environment a ser usado baseado na branch
author: Victor Borges Silva
branding:
  icon: "check-square"
  color: "blue"
inputs:
  prd_branch:
    description: 'Nome da branch para o ambiente de Produção'
    required: true
    default: 'main'
  hml_branch:
    description: 'Nome da branch para o ambiente de Homologação'
    required: true
    default: 'hml'
  dev_branch:
    description: 'Nome da branch para o ambiente de Desenvolvimento'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: Configura environment baseado na branch
      id: set-environment
      shell: bash
      run: |
        echo "Determianndo environment baseado na branch: ${GITHUB_REF}"
        if [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.main_branch }}" ]]; then
          echo "seleciona-ambiente=prd" >> $GITHUB_OUTPUT
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.hml_branch }}" ]]; then
          echo "seleciona-ambiente=hml" >> $GITHUB_OUTPUT
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.dev_branch }}" ]]; then
          echo "seleciona-ambiente=dev" >> $GITHUB_OUTPUT
        else
          echo "seleciona-ambiente=hml" >> $GITHUB_OUTPUT
        fi
outputs:
  seleciona-ambiente:
    description: 'Determina o environment baseado na branch commitada'
    value: ${{ steps.set-environment.outputs.seleciona-ambiente }}  
