name: Determine Environment
description: Determina o environment a ser usado baseado na branch
inputs:
  main_branch:
    description: 'Nome da branch para o ambiente de Produção'
    required: true
    #default: 'main'
  hml_branch:
    description: 'Nome da branch para o ambiente de Homologação'
    required: true
    #default: 'hml'
  dev_branch:
    description: 'Nome da branch para o ambiente de Desenvolvimento'
    required: true
    #default: 'dev'
outputs:
  ambiente:
    description: 'Determina o environment baseado na branch commitada'
runs:
  using: "composite"
  steps:
    - name: Configura environment baseado na branch
      shell: bash
      run: |
        echo "Determining environment based on branch: ${GITHUB_REF}"
        if [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.main_branch }}" ]]; then
          echo "ambiente=prd" >> $GITHUB_ENV
          echo "::set-output name=ambiente::prd"
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.hml_branch }}" ]]; then
          echo "ambiente=hml" >> $GITHUB_ENV
          echo "::set-output name=ambiente::hml"
        elif [[ "${GITHUB_REF}" == "refs/heads/${{ inputs.dev_branch }}" ]]; then
          echo "ambiente=dev" >> $GITHUB_ENV
          echo "::set-output name=ambiente::dev"
        else
          echo "ambiente=hml" >> $GITHUB_ENV
          echo "::set-output name=ambiente::hml"
        fi
